apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: challenge-ins
  namespace: challenge-projeto
  annotations:
  # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ingress-prd-2rp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: challenge-service
            port:
              number: 80
