apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-deploy
  namespace: minikube-projeto
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: minikube-projeto
  template:
    metadata:
      labels:
        app: minikube-projeto
    spec:
      containers:
        - image: josegabriel/web:latest 
          name: minikube-container
          env:
            - name: nome
              valueFrom:
                configMapKeyRef:
                  name: minikube-configmap
                  key: nome
          readinessProbe:
              tcpSocket:
                port: 80
              initialDelaySeconds: 30
              periodSeconds: 10
          livenessProbe:
              tcpSocket:
                port: 80
              initialDelaySeconds: 15
              periodSeconds: 20
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 900Mi
            requests:
              cpu: 200m
              memory: 500Mi
